---
 out_dir: './result_scoring/run_scoring_0610_OOD/'
 dataset_dir: /root/reaction_data/USPTO/OOD_split_USPTO_50k/unimplemented.smi

 batch_size: 128
 shuffle: True
 num_epoch: 1600
 which_optimizer: adam
 learning_rate: 0.001
 weight_decay: 0.0001