---
 out_dir: './result_train/run_reaction_0601_OOD-jump1/'
#  dataset_dir: "/root/reaction_data/USPTO/uspto_50k_train_data_0jump.smi" 
 dataset_dir: /root/reaction_data/USPTO/OOD_split_USPTO_50k/uspto_50k_train_data_1jump_0-8.smi
 which_vocab: "char" # "selfies", "regex", or "char"
 vocab_path: "./vocab/uspto_50k_char_vocab_unmapped.yaml"
 percentage: 1

 rnn_config:
  # size of vocab + <eos> + <sos> + <pad> 
  num_embeddings: 61  # 62 for mapped vocab  and 61 for umapped vocab
  embedding_dim: 256
  rnn_type: "LSTM" # LSTM or GRU
  # rnn
  input_size: 256 # size of the recurrent neural network
  hidden_size: 512
  num_layers: 5
  dropout: 0.1314

 batch_size: 128
 shuffle: True
 num_epoch: 1600
 which_optimizer: adam
 learning_rate: 0.001
 weight_decay: 0.0001