---
 out_dir: '../results/run_31/'
 dataset_dir: "../chembl-data/chembl_28/chembl_28_sqlite/chembl28-cleaned.smi" 
 which_vocab: "char" # "selfies", "regex", or "char"
 vocab_path: "./vocab/chembl_char_vocab.yaml"
 percentage: 1

 rnn_config:
  # embedding
  num_embeddings: 75 # size of vocab + <eos> + <sos> + <pad>. char: 47, regex:75
  embedding_dim: 128
  rnn_type: "GRU" # LSTM or GRU

  # rnn
  input_size: 128 # size of the recurrent neural network
  hidden_size: 512
  num_layers: 3
  dropout: 0

 batch_size: 512
 shuffle: True
 num_epoch: 10
 which_optimizer: adam
 learning_rate: 0.001
 weight_decay: 0.0001