---
 out_dir: '../results/run_5/'
 dataset_dir: "../zinc-smiles/"
 which_vocab: "regex" # "selfies" or "regex"
 vocab_path: "./vocab/regex_vocab.yaml"
 percentage: 0.1

 rnn_config:
  # embedding
  num_embeddings: 105 # size of vocab + <eos> + <sos> + <pad>
  embedding_dim: 256

  # rnn
  input_size: 256 # size of the recurrent neural network
  hidden_size: 1024
  num_layers: 4
  dropout: 0.2

 batch_size: 512
 shuffle: True
 num_epoch: 100
 which_optimizer: sgd
 learning_rate: 0.0015
 weight_decay: 0.0007