---
 out_dir: '../results/run_22/'
 dataset_dir: "../chembl-data/chembl_28/chembl_28_sqlite/chembl28-cleaned.smi" 
 which_vocab: "char" # "selfies", "regex", or "char"
 vocab_path: "./vocab/chembl_char_vocab.yaml"
 percentage: 1

 rnn_config:
  # embedding
  num_embeddings: 47 # size of vocab + <eos> + <sos> + <pad>
  embedding_dim: 512
  rnn_type: "GRU" # LSTM or GRU

  # rnn
  input_size: 512 # size of the recurrent neural network
  hidden_size: 1024
  num_layers: 3
  dropout: 0

 batch_size: 512
 shuffle: True
 num_epoch: 300
 which_optimizer: sgd
 learning_rate: 0.04
 weight_decay: 0.0005