---
 out_dir: '../results/run_2/'
 dataset_dir: "../zinc-smiles/"
 vocab_path: "./vocab/selfies_vocab.yaml"
 percentage: 1.0

 rnn_config:
  # embedding
  num_embeddings: 174 # size of vocab + <eos> + <sos>
  embedding_dim: 256

  # rnn
  input_size: 256 # size of the recurrent neural network
  hidden_size: 1024
  num_layers: 4
  dropout: 0.6

 batch_size: 512
 shuffle: True
 num_epoch: 30
 learning_rate: 0.003
 weight_decay: 0.0007